import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import {
    ClerkProvider,
    SignedIn,
    UserButton,
} from "@clerk/nextjs";
import "./globals.css";

const inter = Inter({
    subsets: ["latin"],
    variable: '--font-inter',
});

const spaceGrotesk = Space_Grotesk({
    subsets: ['latin'],
    variable: '--font-space-grotesk',
});

export const metadata: Metadata = {
    title: "Zebra AI Dashboard",
    description: "Zebra AI SaaS Dashboard generated by Antigravity",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en" className={`dark ${inter.variable} ${spaceGrotesk.variable}`}>
                <head>
                    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet" />
                </head>
                <body className="font-body antialiased">
                    <header className="fixed top-4 right-4 z-[5000] flex items-center gap-4 text-white">
                        <SignedIn>
                            <UserButton />
                        </SignedIn>
                    </header>
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
